[versions]
### Plugins
android = "8.3.0-alpha07"
kotlin = "1.9.20-RC"

### Libraries
# Base
androidx-core = "1.12.0"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"

# UI
android-material = "1.9.0"

# Test
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "android-material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "android" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

